#############
### basic ###
#############

baseURL = "https://blog.wukaige.com"
languageCode = "en-us"
theme = "typo"

title = "wukaige's blog"
license = "MIT"
enableRobotsTXT = true
# googleAnalytics = "UA-1234-5"

ignoreLogs = ['warning-goldmark-raw-html']

##################
### taxonomies ###
##################

[taxonomies]
tag = 'tags'

###############
### outputs ###
###############

[outputs]
home = ["HTML", "RSS"]

##############
### params ###
##############

[params]
# Meta description
description = "A Tech Blog"

# Appearance settings
theme = 'auto'
colorPalette = 'default'
hideHeader = false

# Collection to display on home
homeCollectionTitle = 'Posts'
homeCollection = 'posts'

# Lists parameters
paginationSize = 7
listSummaries = true
listDateFormat = '2 Jan 2006'

# Footer Customization
# showFooter = true
# footerContent = "Your **custom** md `footer`"

[params.author]
name = "wukaige"
email = "email@wukaige.com"

[params.breadcrumbs]
enabled = true
showCurrentPage = true
# home = "~"

# Main menu pages
[[params.menu]]
name = "posts"
url = "/posts"

[[params.menu]]
name = "tags"
url = "/tags"

[[params.menu]]
name = "about"
url = "/about"

[[params.social]]
name = "github"
url = "https://www.github.com/gitduk/"

[[params.social]]
name = "x"
url = "https://x.com/wukaigee/"

##############
### markup ###
##############

[markup]
[markup.highlight]
style = 'algol'
lineNos = false
lineNumbersInTable = false
noClasses = false

